name: Run Tests and Send Report



on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run tests and generate report
      run: |
        pip install pytest
        pytest --junitxml=report.xml || true  # Добавлен "|| true", чтобы не прерывать выполнение на ошибке

    - name: Set result status
      id: result
      run: |
        if grep -q "<failure" report.xml; then
          echo "Tests failed"
          echo "::set-output name=status::failed"
        else
          echo "Tests passed"
          echo "::set-output name=status::passed"
        fi

    - name: Send email with report
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Pytest Report
        body: |
          Hello! Here is your test report from GitHub Actions.
          Test result: ${{ steps.result.outputs.status }}
        to: simpoghosyan4@gmail.com
        from: simpoghosyan4@gmail.com
        attachments: report.xml

